# Configuration for testing

# DB
test_host = "localhost"
test_port = 3306
test_database_indexer = "flare_ftso_indexer_indexer_test"
test_database_main = "flare_ftso_indexer_main_test"
test_username = "root"
test_password = "password"
# Node
test_node_url = "http://coston2.test.aflabs.net:9650/ext/bc/C/rpc"
test_api_key = ""
# Mock chain
test_mock_chain_port = 5500
